package com.example.usersinfo

import java.io.Serializable

data class RandomUser(
    var title: String,
    val photo: String = "",
    val name: String,
    var firstName: String,
    var lastName: String,
    var streetNumber: Int,
    var streetName: String,
    var city: String,
    var state: String,
    var country: String,
    var postcode: Int,
    var latitude: String,
    var longitude: String,
    var offset: String,
    var description: String,
    val email: String,
    var uuid: String,
    val gender: String,
    var username: String,
    var salt: String,
    var md5: String,
    var sha1: String,
    var sha256: String,
    val birthday: String,
    var dateBirth: String,
    val age: Int,
    var ageBirth: Int,
    var dateRegis: String,
    var ageRegis: Int,
    val address: String,
    val phone: String,
    var cell: String,
    val password: String,
    var idName: String,
    var idValue: String?,
    var pictureLarge: String,
    var pictureMedium: String,
    var pictureThumbnail: String,
    var nat: String,
    var seed: String,
    var results: Int,
    var page: Int,
    var version: String
): Serializable
